name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: devops_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
        echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
        echo "DB_USER=root" >> $GITHUB_ENV
        echo "DB_PASSWORD=root" >> $GITHUB_ENV
        echo "DB_NAME=devops_db" >> $GITHUB_ENV
    - name: Wait for MySQL to be ready
      run: |
        sleep 20  # Esperar mientras MySQL inicia
        sudo apt-get install -y default-libmysqlclient-dev

    - name: Run tests
      run: |
        pytest test/test_api.py

    - name: Build Docker Image
      run: docker build -t devops-app .

    - name: Notify Success
      if: success()
      run: echo "✅ Build and Tests passed with success!"

    - name: Notify Failure
      if: failure()
      run: echo "❌ Build or Tests failed!"  
